/**
 * Positive Quote Pool — 400 short Indonesian quotes for the Arme chat
 * greeting random rotation. Curated to be:
 *   - Positive / wholesome (no melancholy, no preachy)
 *   - Bahasa Indonesia natural
 *   - Short (under ~140 chars) for clean blockquote rendering
 *   - Plain text only (no markdown, no emoji)
 *   - Mixed themes (hope, kindness, gratitude, small joys, growth,
 *     memory, friendship, nature, quiet strength, music/stage)
 *
 * Used by getRandomQuote() in quoteOfTheDay.js. NOT used by
 * getQuoteOfTheDay() — the daily rotation stays curated on-brand
 * (Eli/Armeniaca-specific) so the home strip retains its signature.
 *
 * Append-only convention: insertion order does not affect rotation
 * (random pick), but appending preserves diff-friendliness.
 */

export const POSITIVE_QUOTES_POOL = [
  // — Hope & new beginnings —
  'Pagi datang tanpa diminta — kabar baik juga begitu.',
  'Setiap pintu yang tertutup tidak lebih kuat dari pintu yang terbuka.',
  'Hari ini punya halaman kosong; tulis pelan-pelan.',
  'Mimpi yang dipelihara akan tahu jalannya sendiri.',
  'Yang baru tumbuh lebih kuat dari yang dipaksa.',
  'Bintang masih bersinar di langit yang mendung.',
  'Awal lambat tetap awal yang sah.',
  'Esok bukan janji, tapi hadiah.',
  'Bunga di musim semi tahu kapan harus mekar.',
  'Setiap embun pagi adalah catatan ulang.',
  'Yang dimulai hari ini akan dijaga waktu.',
  'Harapan tidak perlu besar untuk hidup.',
  'Pintu kecil bisa membuka ruang luas.',
  'Langkah pertama selalu paling berani.',
  'Sebentar lagi, sebentar lagi — itu cukup.',
  'Apa yang ditanam dengan tenang, panennya juga tenang.',
  'Sinar di celah jendela cukup untuk satu hari.',
  'Kembali bukan mundur, kadang itu istirahat.',
  'Setelah hujan deras, pelangi ingat janjinya.',
  'Hari baik dimulai dari napas yang tenang.',
  'Kabar baik biasanya datang dari arah yang tak terduga.',
  'Yang dimulai dengan niat baik, jalannya akan dirapikan.',
  'Pagi mau dia disambut atau tidak — dia tetap datang.',
  'Setiap Senin punya kemungkinan yang sama dengan Jumat.',
  'Permulaan kecil sering jadi awal yang panjang.',
  'Pelan-pelan adalah cara langit tumbuh.',
  'Jangan kecil hati pada awal yang sederhana.',
  'Hari ini cukup untuk hari ini.',
  'Yang berani memulai sudah setengah jalan.',
  'Setiap matahari terbit adalah maaf yang lembut.',
  'Mimpi tidak hilang, dia cuma menunggu.',
  'Awal yang gugup tetap awal yang sah.',
  'Akar yang dalam tumbuh dari hari-hari biasa.',
  'Yang menunggu dengan sabar tidak pernah benar-benar menunggu.',
  'Tunas pertama adalah berita baik paling jujur.',
  'Esok belum dibuka, tapi sudah disiapkan.',
  'Jalan terbuka untuk yang berjalan.',
  'Yang ditunda sehari tidak hilang.',
  'Pertanda pertama biasanya datang sebagai tenang.',
  'Setiap pagi adalah kesempatan kedua yang gratis.',

  // — Kindness & warmth —
  'Kebaikan kecil tetap kebaikan.',
  'Tutur lembut sampai lebih jauh dari kata keras.',
  'Mendengar adalah bentuk kasih yang sering dilupakan.',
  'Sapaan biasa bisa jadi keajaiban hari ini.',
  'Yang ditolong hari ini, mengingatnya seumur hidup.',
  'Hangat bukan suhu, hangat itu pilihan.',
  'Senyum yang tulus tidak butuh penjelasan.',
  'Memberi waktu juga adalah memberi.',
  'Diam yang menemani lebih berarti dari kata-kata yang penuh.',
  'Tidak semua bantuan terlihat — yang penting datang tepat waktu.',
  'Sapa orang asing, kadang itu satu-satunya sapaan yang dia terima hari ini.',
  'Yang lembut akhirnya menang lebih sering.',
  'Kebaikan tidak punya tanggal kedaluwarsa.',
  'Cangkir teh yang dibagi adalah peluk yang panjang.',
  'Lakukan satu hal baik hari ini, secukupnya.',
  'Tangan yang menolong tidak pernah jadi tangan yang merugi.',
  'Maaf yang tulus bisa menyembuhkan tahun-tahun.',
  'Yang membuka pintu untuk orang lain, dirinya akan menemukan pintu.',
  'Ramah itu mata uang yang nilainya selalu naik.',
  'Berbagi cerita adalah berbagi dunia.',
  'Membantu tanpa menghitung adalah kebaikan paling tulus.',
  'Pelukan hangat lebih kuat dari nasihat panjang.',
  'Senyumannya gratis — tapi nilai-nya tinggi.',
  'Hadirmu sudah jadi hadiah, bahkan kalau diam.',
  'Kebaikan adalah bahasa yang dimengerti semua hati.',
  'Yang baik bukan harus besar — yang penting tulus.',
  'Tatapan yang mengerti adalah obat tanpa nama.',
  'Memberi tanpa pamrih akan kembali sebagai cahaya.',
  'Hangatnya teh kecil bisa memperbaiki sore yang lelah.',
  'Sahabat sejati hadir tanpa diminta.',
  'Bantulah yang lemah, walau dia tidak meminta.',
  'Senyum sederhana sering jadi awal cerita panjang.',
  'Hatimu yang lembut adalah taman bagi yang lelah.',
  'Pertanyaan "kamu baik-baik aja?" bisa selamatkan hari seseorang.',
  'Memaafkan adalah hadiah untuk diri sendiri.',
  'Yang tulus tidak butuh pengakuan untuk terus berbuat baik.',
  'Telapak tangan terbuka lebih banyak menerima dari yang menutup.',
  'Beri tanpa berharap — terima dengan syukur.',
  'Hangatkan dunia mulai dari sebelahmu.',
  'Bahkan kata "halo" bisa jadi cahaya bagi seseorang.',

  // — Gratitude & appreciation —
  'Hal-hal kecil sebenarnya hal yang besar.',
  'Terima kasih yang diucap mengalir balik ke yang mengucapkan.',
  'Hari ini bisa dinikmati tanpa harus sempurna.',
  'Yang dimiliki sekarang sudah cukup untuk satu napas syukur.',
  'Lupa berterima kasih lebih melelahkan dari yang dikira.',
  'Hujan, matahari, semuanya hadiah yang sering lupa dihitung.',
  'Rumah hangat, makan cukup — itu sudah berkah.',
  'Setiap napas adalah pinjaman, syukur adalah balasannya.',
  'Yang berterima kasih melihat lebih banyak dari yang mengeluh.',
  'Yang dilihat dengan syukur tampak lebih cerah.',
  'Terima kasih untuk diri yang sudah sampai sejauh ini.',
  'Hidup yang biasa adalah hadiah yang luar biasa.',
  'Mata yang tahu bersyukur tidak pernah miskin.',
  'Hujan datang tepat saat tanaman butuh — itu cukup ajaib.',
  'Suara tawa anak kecil itu pengingat sederhana.',
  'Hari biasa adalah hari yang banyak rindu di masa depan.',
  'Pagi yang sehat lebih mahal dari emas.',
  'Tetap di sini saja sudah cukup syukur.',
  'Yang banyak orang doakan diam-diam, kamu mungkin punya.',
  'Setiap sore yang tenang adalah berkah yang sering luput.',
  'Yang sederhana dirayakan, yang besar diingat.',
  'Hujan menyiram tanpa diminta — begitu juga rezeki kadang.',
  'Kasih ibu adalah doa yang berjalan.',
  'Lupa terima kasih bikin hati cepat tua.',
  'Bahkan rasa lelah hari ini tanda kamu hidup.',
  'Daun jatuh mengingatkan: ada waktu untuk semuanya.',
  'Yang baik dalam hari ini lebih banyak dari yang disadari.',
  'Setiap nafas adalah catatan baru.',
  'Yang berlalu pun pernah jadi anugerah.',
  'Mata yang melihat keindahan akan menemukannya di mana-mana.',
  'Diam-diam, kebaikan terus datang.',
  'Senyum kecil di pagi hari bisa jadi syukur paling murni.',
  'Tubuh yang sehat adalah doa yang terkabul.',
  'Hari ini cukup walau tak sempurna.',
  'Setiap detik yang berlalu adalah hadiah halus.',
  'Yang punya hati syukur, hidupnya luas.',
  'Sederhana itu bukan sedikit, sederhana itu cukup.',
  'Tidak semua orang bangun pagi ini — kamu salah satu yang beruntung.',
  'Bahkan secangkir teh hangat bisa jadi pengingat cinta.',
  'Syukur tidak menambah harta, tapi menambah lapang hati.',

  // — Small joys —
  'Secangkir teh di sore yang sepi adalah kemewahan.',
  'Buku lama dengan halaman dilipat itu rumah kecil.',
  'Hujan di atap seng adalah lagu pengantar tidur.',
  'Bunga liar di pinggir jalan tetap bunga.',
  'Senja di hari biasa tetap istimewa.',
  'Bau roti pagi adalah bahasa kasih sayang.',
  'Suara hujan di sore yang sepi adalah obat sederhana.',
  'Hangatnya teh manis bisa lebih dari sekadar minuman.',
  'Foto lama yang ditemukan kembali adalah hadiah kecil.',
  'Senyum tanpa alasan adalah bentuk kemerdekaan.',
  'Cahaya kuning di kafe sudut sore — kecil, tapi cukup.',
  'Bagian kerak nasi yang renyah adalah kebahagiaan kecil.',
  'Aroma kopi pagi adalah pelukan dari hari itu sendiri.',
  'Buku yang dibaca pelan di hari sepi terasa seperti rumah.',
  'Lampu jalan yang menyala satu-satu di senja kerasa nostalgic.',
  'Jendela terbuka, angin masuk, hati ringan.',
  'Sepatu yang nyaman bisa bikin hari terasa berbeda.',
  'Mendengar lagu kesukaan di radio tanpa sengaja itu kebetulan manis.',
  'Bermain dengan kucing tetangga adalah meditasi mini.',
  'Setrika hangat di pagi dingin punya keajaibannya sendiri.',
  'Membaca surat lama bisa membuka rasa yang lama tersimpan.',
  'Mandi air hangat setelah hari yang panjang itu surga kecil.',
  'Senyum kucing yang puas adalah motivasi ringan.',
  'Tertawa karena hal kecil bersama teman itu istimewa.',
  'Jalan kaki tanpa tujuan di pagi sejuk itu mewah.',
  'Mendengar suara ombak dari kejauhan adalah lullaby alam.',
  'Bau hujan yang baru turun di tanah kering bikin damai.',
  'Menemukan koin lama di saku bisa bikin senyum lebar.',
  'Tidur sebentar di siang yang lelah adalah liburan kecil.',
  'Sarapan sederhana yang dimakan tenang adalah ritual mahal.',
  'Cokelat panas di hari hujan itu rumah sementara.',
  'Lagu lama yang masih hapal liriknya itu pengingat hangat.',
  'Aroma kayu manis di kue pagi itu kenangan yang tercium.',
  'Senyum tukang sayur langganan adalah berkah pagi.',
  'Cuaca yang pas — tidak terlalu dingin, tidak terlalu panas — itu hadiah.',
  'Bunga mawar di taman tetangga tetap milik mata kita.',
  'Lagu yang muncul di playlist tepat sesuai mood itu sihir kecil.',
  'Telepon dari orang tersayang yang tak terduga membahagiakan.',
  'Aroma laundry baru kering di sore yang sepi itu rumah.',
  'Pensil tajam, kertas kosong — sudah cukup untuk memulai.',

  // — Patience & growth —
  'Yang dipaksa tumbuh, hancur.',
  'Akar paling kuat tumbuh dalam tanah yang sunyi.',
  'Belajar pelan-pelan tetap belajar.',
  'Kalah hari ini tidak berarti kalah selamanya.',
  'Pohon besar dimulai dari biji yang sangat kecil.',
  'Yang sabar dapat tempat duduk paling depan.',
  'Tidak semua pertumbuhan terlihat.',
  'Air mengukir batu bukan karena keras, tapi karena sabar.',
  'Hujan deras membantu, hujan rintik juga.',
  'Yang menunggu dengan tenang tidak ketinggalan apa-apa.',
  'Setiap kesalahan adalah pelajaran dengan biaya yang murah.',
  'Pohon yang kuat tidak tumbuh sekejap mata.',
  'Gagal hari ini tidak menentukan kemarin atau besok.',
  'Yang lambat tumbuh lebih dalam akarnya.',
  'Latihan kecil tiap hari mengalahkan pelatihan besar sekali.',
  'Setiap musim punya pelajaran sendiri.',
  'Belajar dari diri sendiri lebih hemat dari menyalahkan orang.',
  'Yang sulit kemarin jadi mudah hari ini.',
  'Pertanyaan bodoh tidak ada, hanya pertanyaan yang belum ditanya.',
  'Hujan deras tidak abadi, begitu juga ujian.',
  'Yang sabar menikmati buahnya, yang tergesa menumpahkannya.',
  'Hari-hari yang berat sering jadi cerita terbaik.',
  'Diam dan amati — itu sudah pelajaran besar.',
  'Gagal adalah guru yang paling jujur.',
  'Air mengalir mencari jalannya — kamu juga akan.',
  'Tetap bergerak walau pelan, tidak apa-apa.',
  'Yang dilatih sedikit demi sedikit jadi tak bisa diragu.',
  'Kesabaran adalah tabungan yang bunganya tidak kelihatan.',
  'Salah hari ini bisa dibetulkan besok.',
  'Akar yang dalam membuat pohon kuat menghadapi angin.',
  'Tanpa luka, tidak ada penyembuhan.',
  'Tunas baru tumbuh dari pohon yang dipangkas.',
  'Belajar gagal adalah keterampilan paling berguna.',
  'Berhenti sebentar bukan menyerah, kadang itu strategi.',
  'Yang ditakdirkan tumbuh akan tumbuh — meski di celah batu.',
  'Hari ini lebih baik dari kemarin — itu sudah cukup.',
  'Latihan kecil yang konsisten kalahkan bakat yang malas.',
  'Kalah satu pertandingan bukan akhir musim.',
  'Yang menanam hari ini, suatu hari akan dipanen.',
  'Pelan tapi pasti lebih tahan dari cepat tapi rapuh.',

  // — Memory & archive —
  'Yang ditulis perlahan jadi yang diingat lama.',
  'Foto lama tahu cerita yang lupa kita ceritakan.',
  'Halaman buku yang dilipat adalah peta hati.',
  'Yang diingat dengan baik tidak akan hilang.',
  'Arsip yang dirawat tidak pernah kuno.',
  'Setiap kenangan adalah jendela kecil yang bisa dibuka kapan saja.',
  'Catatan harian adalah surat untuk diri di masa depan.',
  'Yang dilupakan dunia, mungkin diingat satu hati.',
  'Setiap foto punya keheningan sendiri.',
  'Yang dirawat lama, tahan lama.',
  'Diari tua adalah teman yang tidak pernah berubah.',
  'Setiap buku tua punya bau yang tidak tergantikan.',
  'Tulisan tangan masih lebih hangat dari ketikan.',
  'Cerita yang dibagi adalah cerita yang abadi.',
  'Yang dijaga kenangannya tidak benar-benar pergi.',
  'Surat lama menyimpan suara yang sudah lama tidak kita dengar.',
  'Foto kabur kadang lebih jujur dari yang tajam.',
  'Catatan ringan hari ini, nostalgia berat tahun depan.',
  'Yang tertulis di kertas tetap, yang tertulis di hati lebih lama.',
  'Album foto adalah perpustakaan emosi.',
  'Setiap kenangan baik adalah harta tanpa beban.',
  'Yang dirawat dengan cinta jadi warisan.',
  'Buku catatan kecil bisa simpan dunia besar.',
  'Foto lama tahu siapa kita sebelum kita lupa.',
  'Yang ditulis pelan sering jadi yang paling jujur.',
  'Cerita yang diingat baik tak pernah benar-benar mati.',
  'Setiap potret adalah waktu yang berhenti sebentar.',
  'Yang disimpan rapi, suatu hari jadi sejarah.',
  'Yang dikenang dengan syukur akan kembali sebagai berkah.',
  'Setiap halaman buku punya jejak jari masa lalu.',
  'Yang dibaca berulang-ulang jadi bagian dari kita.',
  'Foto buram di laci masih punya cerita yang utuh.',
  'Yang dirawat, hidup. Yang dilupakan, hilang.',
  'Setiap nama yang diingat adalah cinta yang dilanjutkan.',
  'Buku lama yang berdebu masih punya banyak yang dikatakan.',
  'Yang dijaga rapi, dilihat anak cucu.',
  'Foto polaroid sederhana bisa lebih mahal dari emas.',
  'Yang ditulis dengan hati tak mudah dilupakan.',
  'Setiap catatan kecil adalah kepingan dari diri.',
  'Arsip yang baik adalah cinta yang sabar.',

  // — Friendship & community —
  'Teman yang baik adalah obat tanpa resep.',
  'Yang menemani saat sepi, mereka yang ingat selamanya.',
  'Bersama lebih ringan dari sendirian, walau tugas sama.',
  'Tertawa bersama menambah umur.',
  'Sahabat yang tulus tidak butuh banyak kata.',
  'Yang menghargai senyummu, jaga baik-baik.',
  'Lingkaran kecil yang hangat lebih berharga dari lingkaran besar yang dingin.',
  'Sahabat sejati datang tanpa undangan, pergi tanpa cemburu.',
  'Yang menanyakan kabar walau jarang ketemu, itu sahabat.',
  'Persahabatan yang tulus tidak bisa dipalsukan.',
  'Yang membantu tanpa diminta lebih dari sekadar teman.',
  'Komunitas yang baik adalah pohon dengan banyak akar.',
  'Suara tawa di antara teman adalah musik paling jujur.',
  'Yang menjaga rahasia kita adalah saudara pilihan.',
  'Berkumpul tanpa agenda adalah kemewahan sederhana.',
  'Sahabat yang baik mengingatkan tanpa menghakimi.',
  'Yang menemani saat berhasil itu kebetulan; yang menemani saat gagal itu sahabat.',
  'Lingkaran kecil tapi tulus lebih berharga dari kerumunan yang tidak peduli.',
  'Persahabatan yang dirawat tumbuh seperti pohon.',
  'Yang memanggilmu dengan nama panggilan lama adalah saksi hidupmu.',
  'Sahabat sejati tahu kapan harus ada, kapan harus diam.',
  'Yang tertawa dengan kita tanpa menyombongkan, itu sahabat.',
  'Persahabatan adalah kebun yang harus disiram berulang.',
  'Yang menerima kekuranganmu adalah hadiah.',
  'Sahabat baru tidak menggantikan yang lama, dia menambah.',
  'Komunitas tumbuh dari satu kebaikan kecil yang konsisten.',
  'Yang menemani perjalanan jauh lebih berharga dari tujuan itu sendiri.',
  'Sahabat yang baik tahu cara hadir tanpa membuat kita merasa rendah.',
  'Yang menjaga kepercayaan kita adalah benteng.',
  'Persahabatan jangka panjang dibangun dari kejujuran kecil.',
  'Sapaan singkat dari teman lama bisa selamatkan hari yang berat.',
  'Yang mendengar tanpa menghakimi adalah anugerah.',
  'Sahabat yang baik mengingatkan siapa kita saat kita lupa.',
  'Bersama mereka yang tulus, sepi pun terasa ramai.',
  'Yang merayakan kemenanganmu tanpa iri adalah hadiah.',
  'Persahabatan tanpa pamrih adalah kekayaan tersembunyi.',
  'Sahabat sejati datang dengan kabar dan diam yang tepat.',
  'Yang mengingat ulang tahunmu walau kamu lupa, jaga baik-baik.',
  'Komunitas kecil yang hangat lebih berharga dari panggung besar.',
  'Sahabat lama adalah perpustakaan hidup yang mengingat kita.',

  // — Nature & seasons —
  'Aprikot mekar tanpa diminta — kebaikan juga begitu.',
  'Pohon tidak terburu-buru, dia tumbuh sesuai musimnya.',
  'Daun gugur bukan akhir, dia jadi tanah baru.',
  'Hujan deras dan rintik sama-sama menyuburkan.',
  'Senja paling indah datang setelah panas yang terik.',
  'Bunga kecil di tepi jalan tetap pantas dilihat.',
  'Akar yang dalam membuat pohon tahan badai.',
  'Setiap musim punya cerita yang berbeda.',
  'Sungai tidak terburu-buru, tapi sampai juga ke laut.',
  'Awan gelap tidak abadi, langit biru kembali.',
  'Bunga yang mekar di tempat yang sulit lebih kuat.',
  'Daun yang jatuh menyuburkan tanah untuk daun baru.',
  'Embun pagi tahu rahasia kesabaran.',
  'Senja yang tenang adalah hadiah harian.',
  'Pohon yang melengkung di angin tidak patah.',
  'Setiap bunga punya waktunya sendiri untuk mekar.',
  'Hujan yang turun lembut juga menumbuhkan biji.',
  'Matahari pagi tahu jalannya, walau ditutupi awan.',
  'Akar tidak terlihat, tapi tanpa dia tidak ada pohon.',
  'Bunga yang mekar di musim semi tidak lupa pada musim dingin.',
  'Pohon tertua biasanya yang paling tahan ditiup angin.',
  'Setiap musim semi datang setelah musim dingin yang sabar.',
  'Sungai berkelok bukan karena lemah — itu cara dia bertahan.',
  'Air dan batu sama-sama abadi, tapi dengan cara berbeda.',
  'Setiap bibit punya potensi hutan.',
  'Daun yang hijau hari ini akan berguguran, dan tumbuh lagi.',
  'Senja paling tenang biasanya datang setelah hari yang panjang.',
  'Pohon kecil di antara pohon besar tetap pohon.',
  'Hujan tidak memilih siapa yang basah.',
  'Setiap musim adalah pengingat: semua berubah, semua kembali.',
  'Bunga liar tidak menunggu apresiasi untuk mekar.',
  'Pohon yang berbuah adalah hadiah dari kesabaran bertahun-tahun.',
  'Akar yang baik menerima air dengan tenang.',
  'Setiap musim semi punya bunga pertama yang istimewa.',
  'Hujan menyuburkan tanpa tahu siapa yang menanam.',
  'Pohon mahoni butuh puluhan tahun untuk berdiri tegak.',
  'Setiap awan punya bayangan, tapi tidak ada yang abadi.',
  'Bumi yang dirawat akan memberi panen.',
  'Bunga aprikot mekar dulu, lalu buahnya menyusul.',
  'Setiap embun pagi adalah memori malam yang tenang.',

  // — Quiet strength —
  'Yang tenang sering lebih kuat dari yang ribut.',
  'Sabar bukan diam, sabar adalah pilihan aktif.',
  'Yang berani tidak berarti tidak takut, tapi tetap melangkah.',
  'Kekuatan sejati tidak perlu pamer.',
  'Yang lembut tidak berarti lemah.',
  'Diam yang tepat lebih bermakna dari teriakan yang kosong.',
  'Yang menerima kekalahan dengan tenang sudah menang.',
  'Air tenang dalam ternyata.',
  'Lembut bukan lemah, halus bukan mudah patah.',
  'Yang sabar mengamati lebih banyak dari yang gegabah.',
  'Diam yang kuat bisa lebih bersuara dari yang berteriak.',
  'Yang menahan amarah hari ini menyelamatkan banyak besok.',
  'Keberanian sejati adalah berkata "tidak" pada yang seharusnya tidak.',
  'Yang sabar di dunia yang gaduh sudah pemenang.',
  'Lembut dengan diri sendiri adalah bentuk kekuatan.',
  'Tenang bukan kosong, tenang adalah kebijaksanaan.',
  'Yang berani mengakui salah lebih kuat dari yang menyembunyikannya.',
  'Sederhana adalah hasil dari banyak pengalaman.',
  'Yang tenang di tengah badai adalah jangkar bagi yang lain.',
  'Diam bukan setuju, kadang diam adalah strategi.',
  'Berhenti sebentar bukan menyerah, itu istirahat untuk lari lagi.',
  'Kekuatan yang halus lebih awet dari yang keras.',
  'Yang lembut menyentuh hati, yang keras menyentuh telinga.',
  'Sabar adalah otot yang dilatih sehari-hari.',
  'Yang tahu kapan berhenti lebih bijak dari yang terus berlari.',
  'Pohon yang kuat melengkung di angin tanpa patah.',
  'Yang menerima takdir dengan tenang tidak benar-benar kalah.',
  'Diam adalah bahasa yang dimengerti bumi.',
  'Yang lembut tahu kapan harus keras, dan kebalikannya.',
  'Berani memaafkan adalah berani yang sering luput.',
  'Yang menahan diri adalah pahlawan tanpa medali.',
  'Diam yang sabar lebih kuat dari kata-kata yang panik.',
  'Yang tenang menerima kritik tanpa rusak.',
  'Lembut adalah hasil dari banyak luka yang sudah disembuhkan.',
  'Yang berdiri tanpa tepuk tangan tetap berdiri.',
  'Sabar bukan menunda, sabar adalah ritme.',
  'Yang tahu diri lebih kuat dari yang menyombong.',
  'Lembut tapi tegas adalah keseimbangan yang langka.',
  'Diam saat marah adalah bentuk kebijaksanaan.',
  'Yang menjaga kata-katanya juga menjaga hatinya.',

  // — Music, stage, art —
  'Setiap suara punya nada uniknya sendiri.',
  'Panggung kecil tetap panggung — yang penting cahayanya tulus.',
  'Lagu yang sederhana sering jadi yang paling lama diingat.',
  'Bait pertama tahu cara membuka cerita.',
  'Senyum di panggung adalah jembatan ke penonton.',
  'Yang menyanyi dengan hati tidak butuh oktaf tertinggi.',
  'Setiap nada yang salah masih bagian dari musik.',
  'Pencipta lagu menulis dengan jari, tapi mendengar dengan hati.',
  'Setiap pertunjukan adalah hadiah yang sekali pakai.',
  'Lampu panggung sederhana sudah cukup untuk cerita yang besar.',
  'Yang bernyanyi tulus tidak peduli pada juri.',
  'Setiap melodi pertama kali dirasakan, baru ditulis.',
  'Panggung kosong adalah halaman yang menunggu.',
  'Tarian sederhana yang tulus melampaui koreografi rumit.',
  'Setiap chord punya tetangga yang tepat.',
  'Cahaya panggung berbeda dengan cahaya matahari, tapi sama hangatnya.',
  'Setiap penonton membawa cerita ke teater.',
  'Drama sederhana yang jujur menyentuh lebih dari spektakel besar.',
  'Yang tampil dengan tulus tidak butuh tepuk tangan paling keras.',
  'Lagu yang dinyanyikan dengan air mata punya kekuatan sendiri.',
  'Setiap akhir konser adalah awal kenangan.',
  'Panggung adalah cermin penonton.',
  'Vokal sederhana dari hati lebih hangat dari teknik tanpa rasa.',
  'Setiap not yang dimainkan adalah pilihan.',
  'Pelukis yang sabar tahu kapan harus menambahkan, kapan mengangkat kuas.',
  'Setiap karya seni adalah surat untuk orang yang belum dikenal.',
  'Garis paling sederhana di kanvas bisa berbicara banyak.',
  'Lukisan terbaik dipersembahkan, bukan disombongkan.',
  'Penyair yang baik mendengar lebih banyak dari bicara.',
  'Sajak pendek yang jujur lebih dalam dari prosa yang panjang.',
  'Setiap stanza tahu kapan harus berhenti.',
  'Tarian yang sederhana, dengan hati, melampaui koreografi yang rumit.',
  'Setiap penampil pernah jadi pemula yang gugup.',
  'Setlist yang baik dirancang dengan hati, bukan algoritma.',
  'Lagu kebangsaan kecil di hati setiap orang adalah pengantar tidur.',
  'Konser di kamar tidur juga konser.',
  'Yang menari sendiri di kamar pun sah disebut penari.',
  'Setiap melodi membawa kenangan yang tidak bisa dijelaskan.',
  'Pertunjukan terbaik bukan yang paling rapi, tapi yang paling jujur.',
  'Setiap tepuk tangan adalah ucapan terima kasih yang lembut.',
];
