/**
 * ImageCard Component
 * High-End Editorial Version
 */

import React, { memo } from 'react';
import { useScrollReveal } from '../../hooks/useScrollReveal';
import { useLightbox } from '../../context/LightboxContext';
import { useGallery } from '../../context';

const ImageCard = memo(function ImageCard({
  image,
  index = 0,
  density = 'comfortable',
  viewMode = 'grid',
}) {
  const { open } = useLightbox();
  const { filteredImages } = useGallery();
  const handleClick = () => open(filteredImages, index);
  const {
    url,
    thumbnail,
    webpSrcSet,
    avifSrcSet,
    alt,
    dimensions,
    title,
  } = image;

  const { elementRef, isVisible } = useScrollReveal({
    threshold: 0.05,
    rootMargin: '100px',
    triggerOnce: true,
  });

  const animationDelay = `${Math.min(index * 50, 500)}ms`;
  const aspectByView = {
    grid: {
      compact: '120%',
      comfortable: '140%',
      editorial: '165%',
    },
    timeline: {
      compact: '70%',
      comfortable: '80%',
      editorial: '95%',
    },
    moodboard: {
      compact: '115%',
      comfortable: '130%',
      editorial: '150%',
    },
  };
  const paddingBottom = aspectByView[viewMode]?.[density] || '140%';

  return (
    <article
      ref={elementRef}
      className={`
        group relative overflow-hidden rounded-[2rem]
        bg-[color:var(--retro-bg-primary)] shadow-retro
        transform transition-all duration-700 ease-out
        ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-8'}
      `}
      style={{ transitionDelay: animationDelay }}
      role="listitem"
    >
      <button
        type="button"
        onClick={handleClick}
        aria-label={`Buka frame: ${alt || title || 'Eli JKT48'}`}
        className="block relative overflow-hidden w-full cursor-zoom-in text-left"
        style={{ paddingBottom }}
      >
        {/* Image — picture element negotiates AVIF -> WebP -> JPG. Sources
            map to /public/archive/img-XXX.{avif,webp} variants generated by
            scripts/optimize-images.js (idempotent; safe if files missing
            because the JPG <img> is the final fallback). */}
        <picture>
          {avifSrcSet && <source srcSet={avifSrcSet} type="image/avif" />}
          {webpSrcSet && <source srcSet={webpSrcSet} type="image/webp" />}
          <img
            src={thumbnail || url}
            alt={alt || title}
            loading="lazy"
            decoding="async"
            width={dimensions?.width}
            height={dimensions?.height}
            sizes="(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 33vw"
            className="absolute inset-0 w-full h-full object-cover"
          />
        </picture>
      </button>
    </article>
  );
});

export default ImageCard;
